service: broadband-agol

#frameworkVersion: '2 || 3'

custom:
  pythonRequirements:
    dockerizePip: true
    useStaticCache: false
    zip: true
    # seems like slim cannot be true for geopandas to work
    # slim: true
    pipCmdExtraArgs:
      - --no-deps

provider:
  name: aws
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: 'arn:aws:s3:::broadband-agol-data'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::broadband-agol-data/*'
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  memorySize: 2048
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}

functions:
  broadband:
    handler: handler.broadband
    events: 
      - http: 
          path: broadband
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-python-requirements
