service: broadband-agol

#frameworkVersion: '2 || 3'

package:
  patterns:
    - '!gpkgs/**'

custom:
  pythonRequirements:
    dockerizePip: true
    useStaticCache: false
    zip: true
    # seems like slim cannot be true for geopandas to work
    # slim: true
    pipCmdExtraArgs:
      - --no-deps

provider:
  name: aws
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: 'arn:aws:s3:::broadband-agol-data'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::broadband-agol-data/*'
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
  # iam:
  #   role:
  #     name: broadband-agol-s3
  #     statements: 
  #       - Effect: Allow
  #         Action:
  #           - 's3:*'
  #         Resource: arn:aws:s3:::broadband-agol-data/*

functions:
  broadband:
    handler: broadband.handler
    timeout: 300
    memorySize: 4096
  receive: 
    handler: receive.handler
    timeout: 30
    memorySize: 128
    iamRoleStatements:
      # Allow to invoke other lambda function
      - Effect: Allow
        Action:
          - 'lambda:InvokeFunction'
          - 'lambda:InvokeAsync'
        Resource:
          - arn:aws:lambda:us-east-1:104538610210:function:broadband-agol-beta-broadband
    events: 
      - http: 
          path: broadband
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-iam-roles-per-function
