service: broadband-agol

#frameworkVersion: '2 || 3'

custom:
  pythonRequirements:
    dockerizePip: true
    useStaticCache: false
    zip: true
    # seems like slim cannot be true for geopandas to work
    # slim: true
    pipCmdExtraArgs:
      - --no-deps

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  memorySize: 2048
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}

functions:
  broadband:
    handler: handler.broadband
    events: 
      - http: 
          path: broadband
          method: post
          cors: true
    iamRoleStatementsName: broadband-agol-s3
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3: GetObject
        Resource: arn:aws:s3:::broadband-agol-data

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-iam-roles-per-function
