service: broadband-agol

#frameworkVersion: '2 || 3'

custom:
  pythonRequirements:
    # dockerizePip: 'non-linux'
    zip: true

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  memorySize: 2048
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}

functions:
  broadband:
    handler: handler.broadband
    events: 
      - http: 
          path: broadband
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-python-requirements
